name: Salesforce X Netflix
title: Learn Salesforce | By Building Application for Netflix
description: Salesforce X Netflix Is Bootcamp where i will be building salesforce app for netflix.
tags:
  - salesforce
  - bootcamp
  - Learn Salesforce from scratch
  - salesforce projects
  - Salesforce X Netflix
show_hero: true
menu:
  - title: Home
    url: /
  - title: Table Of Content
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: imswarnil@gmail.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
